version: '3.5'

services:

  zipline:
    build: .
    image: zipline
    container_name: zipline
    ports:
      - "8888:8888"

    volumes:
      - type: bind
        source: ./notebooks
        target: /home/brent/.jupyter/notebooks
      - type: bind
        source: ./lib
        target: /home/brent/.jupyter/lib
      - type: bind
        source: ./private_data
        target: /home/brent/.jupyter/private_data
